# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94796b55f73424768647c4fe540beb031680034e018c210303b5c6000d18749db644f60cf6a26a5216d946273830460e35ffc79536eb750e1b82329db202c609

test:
  secret_key_base: f8ef275bb512dd7d5fccddfe5cb4f3affcc69c632ee804ad3f7fc923efbfae792dced75f0f573ac7b6952f13d03fa654ce61f22465cb7746f66b110ab5b00c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
